engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "./.phpmd.xml"

ratings:
  paths:
    - "src/**.php"

exclude_paths:
  - tests
  - artifacts
  - bin
  - res
