language: php
sudo: false

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

before_install:
  - composer config -g github-oauth.github.com cdd81c1c1dc62a6251e7622544d9f9cbd95d6ab5
  - composer config -g repositories.packagist composer http://packagist.jp
  - composer global require hirak/prestissimo

install:
  - composer install --no-progress --profile

script:
  - composer test

after_success:
  - php bin/ocular.phar code-coverage:upload --format=php-clover artifacts/clover.xml
  - php bin/coveralls.phar -v

matrix:
  allow_failures:
    - php: hhvm
